version: '2'
services:
  openldap-authentication:
    image: osixia/openldap:1.1.9
    environment:
      KEEP_EXISTING_CONFIG: 'false'
      LDAP_ADMIN_PASSWORD: '123456'
      LDAP_BACKEND: MDB
      LDAP_BASE_DN: dc=ldapdocker,dc=doc
      LDAP_CONFIG_PASSWORD: config
      LDAP_DOMAIN: ldapdocker.doc
      LDAP_LOG_LEVEL: '256'
      LDAP_ORGANISATION: LDAP Docker.
      LDAP_READONLY_USER: 'false'
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'false'
      LDAP_REPLICATION: 'false'
      LDAP_RFC2307BIS_SCHEMA: 'false'
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_TLS: 'true'
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_ENFORCE: 'false'
      LDAP_TLS_PROTOCOL_MIN: '3.1'
      LDAP_TLS_VERIFY_CLIENT: demand
    stdin_open: true
    tty: true
    ports:
    - 389:389/tcp
    - 636:636/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: machine=cluster-flowz

  openldapadmin-authentication:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
      PHPLDAPADMIN_LDAP_HOSTS: openldap-authentication
    stdin_open: true
    tty: true
    ports:
    - 18080:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: machine=cluster-flowz

  auth-authentication-flowz:
    image: obdev/authentication_auth_flowz:dev
    environment:
      MONGODB: mongodb://obdev2:123456789@ds125966-a0.mlab.com:25966/closeoutpromo
      SECRET: abcdefgabcdefg
    stdin_open: true
    tty: true
    ports:
    - 3001:3001/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: machine=cluster-flowz

  ldap-authentication-flowz:
    image: obdev/authentication_ldap_flowz:dev
    environment:
      SECRET: abcdefgabcdefg
      LDAPURL: ldap://openldap-authentication
      ADMINPASS: '123456'
      USERPASS: '123'
    stdin_open: true
    tty: true
    ports:
    - 3000:3000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: machine=cluster-flowz

  user-authentication-flowz:
    image: obdev/authentication_user_flowz:dev
    environment:
      MONGODB: mongodb://obdev2:123456789@ds125966-a0.mlab.com:25966/closeoutpromo
      SECRET: abcdefgabcdefg
    stdin_open: true
    tty: true
    ports:
    - 3002:3002/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: machine=cluster-flowz

